# This is a basic workflow to push repo to HF

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name:  Add remote
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space https://tbeal:$HF@huggingface.com/spaces/trentbeal/quick-demo
      - name:  Push to hub
        env:
          HF: ${{ secrets.HF }}
        run: git push --force https://trentbeal:$HF@huggingface.co/spaces/trentbeal/quick-demo main
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
